---
language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      install:
        - go get -u github.com/golang/dep/cmd/dep
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - dep ensure
      os: linux
      go: master
      script:
        - go build .
        - go test .
        - go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN