---
language: go
sudo: false
notifications:
  email: joaosoft@gmail.com
jobs:
  include:
    - stage: test
      install:
        - go mod tidy
        - go mod vendor
      os: linux
      go: master
      script:
        - go build -o ./dynamodb/dynamodb ./dynamodb/main.go
        - go test ./dynamodb
        - go test -coverprofile=coverage.txt -covermode=atomic ./dynamodb
        - go test ./dynamodb -bench=. -cpu=1,2,4,8

      after_success:
        - bash <(curl -s https://codecov.io/bash)