---
language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      install:
        - go get -u github.com/golang/dep/cmd/dep
        - dep ensure
      os: linux
      go: master
      script:
        - go build .
        - go test .