---
language: go
sudo: false
notifications:
  email: joaosoft@gmail.com
jobs:
  include:
    - stage: test
      install:
        - go get github.com/joaosoft/dependency
        - dependency get
      os: linux
      go: master
      script:
        - go build ./dynamodb
        - go test ./dynamodb
        - go test -coverprofile=coverage.txt -covermode=atomic ./dynamodb
        - go test ./dynamodb -bench=. -cpu=1,2,4,8

      after_success:
        - bash <(curl -s https://codecov.io/bash)