---
language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      install:
        - go get -v github.com/Masterminds/glide
        - cd $GOPATH/src/github.com/Masterminds/glide
        - go install
        - cd joaosoft/go-manager
        - glide install
      os: linux
      go: master
      script:
        - go build .
        - go test .