version: '3.3'
services:

  aws.dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: aws.dynamodb
    volumes:
      - "$HOME/docker/dynamodb:/opt/dynamodb-storage:rw"
    ports:
      - 8001:8000
    networks:
      default:
        aliases:
          - dynamodb

  aws.rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: aws.rabbitmq
    hostname: rabbitmq
    environment:
        RABBITMQ_DEFAULT_VHOST: local
        RABBITMQ_DEFAULT_USER:  root
        RABBITMQ_DEFAULT_PASS:  password
    volumes:
      - "$HOME/docker/rabbitmq:/var/lib/rabbitmq:rw"
    ports:
        - 15673:15672
        - 5673:5672
    networks:
      default:
        aliases:
          - rabbitmq

  aws.elasticsearch:
    image: elasticsearch:latest
    container_name: aws.elasticsearch
    environment:
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    volumes:
      - "$HOME/docker/elastic:/usr/share/elasticsearch/data:rw"
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      default:
        aliases:
          - elasticsearch

volumes:
  esdata1:
    driver: local
