version: '3.1'
services:
  database:
    build:
      context: ./docker/
      dockerfile: ./database.dockerfile
    ports:
      - 7000:5432

  nsqlookup:
    image: nsqio/nsq
    container_name: nsqlookup
    hostname: nsqlookup
    ports:
      - 4160:4160
      - 4161:4161
    command: /nsqlookupd

  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    ports:
      - 4150:4150
      - 4151:4151
    links:
      - nsqlookup:nsqlookup
    command: /nsqd --lookupd-tcp-address=nsqlookup:4160

  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - 4171:4171
    command: /nsqadmin --lookupd-http-address=nsqlookup:4161

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 7100:6379

  elasticsearch:
    build:
      context: ./docker/
      dockerfile: ./elasticsearch.dockerfile
    container_name: elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  cassandra-1:
    hostname: cassandra-1
    image: cassandra:latest
    container_name: cassandra-1
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
    #   - ./data/cassandra-1:/var/lib/cassandra:rw

  cassandra-2:
    hostname: cassandra-2
    image: cassandra:latest
    container_name: cassandra-2
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    links:
      - cassandra-1
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
    #   - ./data/cassandra-2:/var/lib/cassandra:rw

volumes:
  esdata1:
    driver: local
