---
language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      install:
        - go get -u honnef.co/go/tools/cmd/{gosimple,staticcheck}
        - npm install -g codeclimate-test-reporter
        - go get -v github.com/Masterminds/glide
        - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
        - glide install
      env:
        - DEPTESTBYPASS501=1
      os: linux
      go: 1.8.x
      script:
        - go build -v .
